<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.7.1" />
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.15" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.19" />
    <PackageReference Include="TencentCloudSDK" Version="3.0.1363" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\kevin.Cache\kevin.Cache.csproj" />
    <ProjectReference Include="..\Kevin.Common\Kevin.Common.csproj" />
  </ItemGroup>

</Project>
