// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Database;

#nullable disable

namespace Kevin.Repository.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20220323054230_初始化Mysql表")]
    partial class 初始化Mysql表
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Repository.Database.TAlipayKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<string>("AesKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("aeskey")
                        .HasComment("支付宝加密解密密钥");

                    b.Property<string>("AlipayPublicKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("alipaypublickey")
                        .HasComment("支付宝公钥");

                    b.Property<string>("AppId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("appid")
                        .HasComment("AppId");

                    b.Property<string>("AppPrivateKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("appprivatekey")
                        .HasComment("App私钥");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks")
                        .HasComment("备注");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.ToTable("t_alipaykey", (string)null);

                    b.HasComment("支付宝平台账户配置表");
                });

            modelBuilder.Entity("Repository.Database.TArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<string>("Abstract")
                        .HasColumnType("longtext")
                        .HasColumnName("abstract")
                        .HasComment("摘要");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("categoryid")
                        .HasComment("类别ID");

                    b.Property<int>("ClickCount")
                        .HasColumnType("int")
                        .HasColumnName("clickcount")
                        .HasComment("点击数");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content")
                        .HasComment("内容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<ulong>("IsDisplay")
                        .HasColumnType("bit")
                        .HasColumnName("isdisplay")
                        .HasComment("是否显示");

                    b.Property<ulong>("IsRecommend")
                        .HasColumnType("bit")
                        .HasColumnName("isrecommend")
                        .HasComment("是否推荐");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title")
                        .HasComment("标题");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.ToTable("t_article", (string)null);

                    b.HasComment("文章表");
                });

            modelBuilder.Entity("Repository.Database.TCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("channelid")
                        .HasComment("频道ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("栏目名目");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parentid")
                        .HasComment("父级栏目ID");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks")
                        .HasComment("备注");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("ParentId");

                    b.ToTable("t_category", (string)null);

                    b.HasComment("栏目信息表");
                });

            modelBuilder.Entity("Repository.Database.TChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("频道名称");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks")
                        .HasComment("备注");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.ToTable("t_channel", (string)null);

                    b.HasComment("频道信息表");
                });

            modelBuilder.Entity("Repository.Database.TCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count")
                        .HasComment("计数");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag")
                        .HasComment("标记");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatetime")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("t_count", (string)null);

                    b.HasComment("计数表");
                });

            modelBuilder.Entity("Repository.Database.TDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key")
                        .HasComment("键");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value")
                        .HasComment("值");

                    b.HasKey("Id");

                    b.ToTable("t_dictionary", (string)null);

                    b.HasComment("字典信息表");
                });

            modelBuilder.Entity("Repository.Database.TFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("文件名称");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("path")
                        .HasComment("保存路径");

                    b.Property<string>("Sign")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sign")
                        .HasComment("标记");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("Table")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table")
                        .HasComment("外链表名");

                    b.Property<Guid>("TableId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tableid")
                        .HasComment("外链表ID");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("TableId");

                    b.ToTable("t_file", (string)null);

                    b.HasComment("文件表");
                });

            modelBuilder.Entity("Repository.Database.TFileGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("fileid")
                        .HasComment("文件ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<ulong>("Isfull")
                        .HasColumnType("bit")
                        .HasColumnName("isfull")
                        .HasComment("是否已完整传输");

                    b.Property<ulong>("Issynthesis")
                        .HasColumnType("bit")
                        .HasColumnName("issynthesis")
                        .HasComment("合成状态");

                    b.Property<int>("Slicing")
                        .HasColumnType("int")
                        .HasColumnName("slicing")
                        .HasComment("分片数");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Unique")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("unique")
                        .HasComment("文件唯一值");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatetime")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("t_filegroup", (string)null);

                    b.HasComment("文件分片上传状态记录表");
                });

            modelBuilder.Entity("Repository.Database.TFileGroupFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("fileid")
                        .HasComment("文件ID");

                    b.Property<int>("Index")
                        .HasColumnType("int")
                        .HasColumnName("index")
                        .HasComment("文件索引值");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Path")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("path")
                        .HasComment("文件保存路径");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("t_filegroupfile", (string)null);

                    b.HasComment("分片上传时的切片文件记录表");
                });

            modelBuilder.Entity("Repository.Database.TImgBaiduAI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("fileid")
                        .HasComment("图片文件ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Result")
                        .HasColumnType("longtext")
                        .HasColumnName("result")
                        .HasComment("接口返回值");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Unique")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unique")
                        .HasComment("图片库唯一标识符");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatetime")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("t_imgbaiduai", (string)null);

                    b.HasComment("产品图片对应百度AI信息表");
                });

            modelBuilder.Entity("Repository.Database.TLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasComment("名称");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks")
                        .HasComment("备注");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("url")
                        .HasComment("地址");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.ToTable("t_link", (string)null);

                    b.HasComment("友情链接表");
                });

            modelBuilder.Entity("Repository.Database.TLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content")
                        .HasComment("内容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Sign")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sign")
                        .HasComment("标记");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type")
                        .HasComment("类型");

                    b.HasKey("Id");

                    b.ToTable("t_log", (string)null);

                    b.HasComment("日志表");
                });

            modelBuilder.Entity("Repository.Database.TOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("orderno")
                        .HasComment("订单号");

                    b.Property<decimal>("PayPrice")
                        .HasColumnType("decimal(38,2)")
                        .HasColumnName("payprice")
                        .HasComment("实际支付金额");

                    b.Property<ulong>("PayState")
                        .HasColumnType("bit")
                        .HasColumnName("paystate")
                        .HasComment("支付状态");

                    b.Property<DateTime?>("PayTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("paytime")
                        .HasComment("支付时间");

                    b.Property<string>("PayType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("paytype")
                        .HasComment("支付方式");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,2)")
                        .HasColumnName("price")
                        .HasComment("价格");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serialno")
                        .HasComment("支付流水号");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state")
                        .HasComment("订单状态");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type")
                        .HasComment("订单类型");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatetime")
                        .HasComment("更新时间");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("updateuserid")
                        .HasComment("编辑人ID");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_order", (string)null);

                    b.HasComment("订单表");
                });

            modelBuilder.Entity("Repository.Database.TOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number")
                        .HasComment("产品数量");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("orderid")
                        .HasComment("订单ID");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("productid")
                        .HasComment("产品ID");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("t_orderdetail", (string)null);

                    b.HasComment("订单详情表");
                });

            modelBuilder.Entity("Repository.Database.TOSLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<Guid?>("ActionUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("actionuserid")
                        .HasComment("操作人信息");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content")
                        .HasComment("变动内容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<string>("DeviceMark")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("devicemark")
                        .HasComment("设备标记");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ipaddress")
                        .HasComment("Ip地址");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks")
                        .HasComment("备注");

                    b.Property<string>("Sign")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sign")
                        .HasComment("标记");

                    b.Property<string>("Table")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table")
                        .HasComment("外链表名");

                    b.Property<Guid>("TableId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tableid")
                        .HasComment("外链表ID");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("ActionUserId");

                    b.HasIndex("TableId");

                    b.ToTable("t_oslog", (string)null);

                    b.HasComment("TOSLog");
                });

            modelBuilder.Entity("Repository.Database.TPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action")
                        .HasComment("Action;");

                    b.Property<string>("ActionName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("actionname")
                        .HasComment("动作名;");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("area")
                        .HasComment("区域名称;");

                    b.Property<string>("AreaName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("areaname")
                        .HasComment("区域;");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<string>("FullName")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("fullname")
                        .HasComment("模块全名;");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("httpmethod")
                        .HasComment("Method;");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icon")
                        .HasComment("图标;");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<bool?>("IsManual")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ismanual")
                        .HasComment("手动添加;");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("module")
                        .HasComment("Module;");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modulename")
                        .HasComment("模块名;");

                    b.Property<int?>("Seq")
                        .HasColumnType("int")
                        .HasColumnName("seq")
                        .HasComment("序号;");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("updateuserid")
                        .HasComment("编辑人ID");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedtime")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_permission", (string)null);

                    b.HasComment("系统权限表");
                });

            modelBuilder.Entity("Repository.Database.TProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("detail")
                        .HasComment("描述");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name")
                        .HasComment("名称");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38,2)")
                        .HasColumnName("price")
                        .HasComment("价格");

                    b.Property<string>("SKU")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sku")
                        .HasComment("SKU");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatetime")
                        .HasComment("更新时间");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("updateuserid")
                        .HasComment("编辑人ID");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("t_product", (string)null);

                    b.HasComment("产品表");
                });

            modelBuilder.Entity("Repository.Database.TRegionArea", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("area")
                        .HasComment("区域名称");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("cityid")
                        .HasComment("所属城市ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("t_regionarea", (string)null);

                    b.HasComment("区域信息表");
                });

            modelBuilder.Entity("Repository.Database.TRegionCity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("city")
                        .HasComment("城市名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("provinceid")
                        .HasComment("所属省份ID");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("t_regioncity", (string)null);

                    b.HasComment("城市信息表");
                });

            modelBuilder.Entity("Repository.Database.TRegionProvince", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Province")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("province")
                        .HasComment("省份");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.ToTable("t_regionprovince", (string)null);

                    b.HasComment("省份信息表");
                });

            modelBuilder.Entity("Repository.Database.TRegionTown", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("areaid")
                        .HasComment("所属区域ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Town")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("town")
                        .HasComment("街道名称");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("t_regiontown", (string)null);

                    b.HasComment("TRegionTown");
                });

            modelBuilder.Entity("Repository.Database.TRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("角色名称");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks")
                        .HasComment("备注信息");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.ToTable("t_role", (string)null);

                    b.HasComment("角色信息表");
                });

            modelBuilder.Entity("Repository.Database.TRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("PermissionId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("permissionid")
                        .HasComment("权限编号;");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("roleid")
                        .HasComment("角色编号;");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("t_rolepermission", (string)null);

                    b.HasComment("TRolePermission");
                });

            modelBuilder.Entity("Repository.Database.TSign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("createuserid")
                        .HasComment("创建人ID");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleteuserid")
                        .HasComment("删除人ID");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Sign")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("sign")
                        .HasComment("自定义标记");

                    b.Property<string>("Table")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("table")
                        .HasComment("外链表名称");

                    b.Property<Guid>("TableId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tableid")
                        .HasComment("外链记录ID");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("DeleteUserId");

                    b.HasIndex("TableId");

                    b.ToTable("t_sign", (string)null);

                    b.HasComment("点赞或标记喜欢记录表");
                });

            modelBuilder.Entity("Repository.Database.TUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email")
                        .HasComment("邮箱");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<ulong>("IsSuperAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("issuperadmin")
                        .HasComment("是否超级管理员");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name")
                        .HasComment("用户名");

                    b.Property<string>("NickName")
                        .HasColumnType("longtext")
                        .HasColumnName("nickname")
                        .HasComment("昵称");

                    b.Property<string>("PassWord")
                        .HasColumnType("longtext")
                        .HasColumnName("password")
                        .HasComment("密码");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone")
                        .HasComment("手机号");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("roleid")
                        .HasComment("角色信息");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatetime")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("t_user", (string)null);

                    b.HasComment("用户表");
                });

            modelBuilder.Entity("Repository.Database.TUserBindAlipay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<Guid>("AlipayKeyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("alipaykeyid")
                        .HasComment("关联支付宝账户");

                    b.Property<string>("AlipayUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("alipayuserid")
                        .HasComment("支付宝UserId");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid")
                        .HasComment("用户ID");

                    b.HasKey("Id");

                    b.HasIndex("AlipayKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("t_userbindalipay", (string)null);

                    b.HasComment("用户和支付宝绑定关系表");
                });

            modelBuilder.Entity("Repository.Database.TUserBindWeixin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid")
                        .HasComment("用户ID");

                    b.Property<Guid>("WeiXinKeyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("weixinkeyid")
                        .HasComment("关联微信账户");

                    b.Property<string>("WeiXinOpenId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("weixinopenid")
                        .HasComment("微信OpenId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeiXinKeyId");

                    b.ToTable("t_userbindweixin", (string)null);

                    b.HasComment("用户和微信绑定关系表");
                });

            modelBuilder.Entity("Repository.Database.TUserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address")
                        .HasComment("地址详细信息");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("company")
                        .HasComment("公司名称");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("position")
                        .HasComment("职务");

                    b.Property<string>("QQ")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("qq")
                        .HasComment("QQ");

                    b.Property<int>("RegionAreaId")
                        .HasColumnType("int")
                        .HasColumnName("regionareaid")
                        .HasComment("地址区域ID");

                    b.Property<bool?>("Sex")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sex")
                        .HasComment("性别");

                    b.Property<string>("Signature")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("signature")
                        .HasComment("个性签名");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid")
                        .HasComment("用户ID");

                    b.Property<string>("WeChat")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("wechat")
                        .HasComment("微信号");

                    b.HasKey("Id");

                    b.HasIndex("RegionAreaId");

                    b.HasIndex("UserId");

                    b.ToTable("t_userinfo", (string)null);

                    b.HasComment("用户详细信息表");
                });

            modelBuilder.Entity("Repository.Database.TWebInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("标识ID");

                    b.Property<string>("FootCode")
                        .HasColumnType("longtext")
                        .HasColumnName("footcode")
                        .HasComment("网站底部代码");

                    b.Property<string>("ManagerAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("manageraddress")
                        .HasComment("管理者地址");

                    b.Property<string>("ManagerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manageremail")
                        .HasComment("管理者邮箱");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("managername")
                        .HasComment("管理者名称");

                    b.Property<string>("ManagerPhone")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("managerphone")
                        .HasComment("管理者电话");

                    b.Property<string>("RecordNumber")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("recordnumber")
                        .HasComment("网站备案号");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("seodescription")
                        .HasComment("SEO描述");

                    b.Property<string>("SeoKeyWords")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("seokeywords")
                        .HasComment("SEO关键字");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("seotitle")
                        .HasComment("SEO标题");

                    b.Property<string>("WebUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("weburl")
                        .HasComment("网站域名");

                    b.HasKey("Id");

                    b.ToTable("t_webinfo", (string)null);

                    b.HasComment("网站信息配置表");
                });

            modelBuilder.Entity("Repository.Database.TWeiXinKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .HasComment("主键标识ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createtime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletetime")
                        .HasComment("删除时间");

                    b.Property<ulong>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("isdelete")
                        .HasComment("是否删除");

                    b.Property<string>("MchId")
                        .HasColumnType("longtext")
                        .HasColumnName("mchid")
                        .HasComment("MchId");

                    b.Property<string>("MchKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mchkey")
                        .HasComment("MchKey\r\n            ]");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("remarks")
                        .HasComment("备注");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasColumnName("sort")
                        .HasComment("排序");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext")
                        .HasColumnName("tenantid")
                        .HasComment("租户ID;");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type")
                        .HasComment("AppId 类型，['App','MiniApp','H5','Native']");

                    b.Property<string>("WxAppId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("wxappid")
                        .HasComment("WxAppId");

                    b.Property<string>("WxAppSecret")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("wxappsecret")
                        .HasComment("WxAppSecret");

                    b.HasKey("Id");

                    b.ToTable("t_weixinkey", (string)null);

                    b.HasComment("微信商户平台账户配置表");
                });

            modelBuilder.Entity("Repository.Database.TArticle", b =>
                {
                    b.HasOne("Repository.Database.TCategory", "Category")
                        .WithMany("TArticle")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TCategory", b =>
                {
                    b.HasOne("Repository.Database.TChannel", "Channel")
                        .WithMany("TCategory")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Channel");

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Repository.Database.TChannel", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TFile", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TFileGroup", b =>
                {
                    b.HasOne("Repository.Database.TFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Repository.Database.TFileGroupFile", b =>
                {
                    b.HasOne("Repository.Database.TFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Repository.Database.TImgBaiduAI", b =>
                {
                    b.HasOne("Repository.Database.TFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Repository.Database.TLink", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TOrder", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TOrderDetail", b =>
                {
                    b.HasOne("Repository.Database.TOrder", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Repository.Database.TOSLog", b =>
                {
                    b.HasOne("Repository.Database.TUser", "ActionUser")
                        .WithMany()
                        .HasForeignKey("ActionUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionUser");
                });

            modelBuilder.Entity("Repository.Database.TPermission", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TProduct", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("Repository.Database.TRegionArea", b =>
                {
                    b.HasOne("Repository.Database.TRegionCity", "City")
                        .WithMany("TRegionArea")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Repository.Database.TRegionCity", b =>
                {
                    b.HasOne("Repository.Database.TRegionProvince", "Province")
                        .WithMany("TRegionCity")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Repository.Database.TRegionTown", b =>
                {
                    b.HasOne("Repository.Database.TRegionArea", "Area")
                        .WithMany("TRegionTown")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Repository.Database.TRolePermission", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TPermission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Database.TRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Repository.Database.TSign", b =>
                {
                    b.HasOne("Repository.Database.TUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "DeleteUser")
                        .WithMany()
                        .HasForeignKey("DeleteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");

                    b.Navigation("DeleteUser");
                });

            modelBuilder.Entity("Repository.Database.TUser", b =>
                {
                    b.HasOne("Repository.Database.TRole", "Role")
                        .WithMany("RoleUserList")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Repository.Database.TUserBindAlipay", b =>
                {
                    b.HasOne("Repository.Database.TAlipayKey", "AlipayKey")
                        .WithMany()
                        .HasForeignKey("AlipayKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlipayKey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Database.TUserBindWeixin", b =>
                {
                    b.HasOne("Repository.Database.TUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TWeiXinKey", "WeiXinKey")
                        .WithMany()
                        .HasForeignKey("WeiXinKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WeiXinKey");
                });

            modelBuilder.Entity("Repository.Database.TUserInfo", b =>
                {
                    b.HasOne("Repository.Database.TRegionArea", "RegionArea")
                        .WithMany()
                        .HasForeignKey("RegionAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Database.TUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegionArea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Database.TCategory", b =>
                {
                    b.Navigation("TArticle");
                });

            modelBuilder.Entity("Repository.Database.TChannel", b =>
                {
                    b.Navigation("TCategory");
                });

            modelBuilder.Entity("Repository.Database.TOrder", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Repository.Database.TRegionArea", b =>
                {
                    b.Navigation("TRegionTown");
                });

            modelBuilder.Entity("Repository.Database.TRegionCity", b =>
                {
                    b.Navigation("TRegionArea");
                });

            modelBuilder.Entity("Repository.Database.TRegionProvince", b =>
                {
                    b.Navigation("TRegionCity");
                });

            modelBuilder.Entity("Repository.Database.TRole", b =>
                {
                    b.Navigation("RoleUserList");
                });
#pragma warning restore 612, 618
        }
    }
}
