using kevin.Domain.Configuration;
using Kevin.Common.App;

namespace kevin.Domain.BaseDatas
{
    public class TPermissionBaseDatas
    {
        public static List<TPermission> Data { get; set; } = new List<TPermission>()
        {
           new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/Home",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="Home",
               ModuleName="首页",
               Action="Home",
               ActionName="首页",
               FullName="菜单/首页",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
           new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/Home/Index",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="Home",
               ModuleName="首页",
               Action="Index",
               ActionName="首页",
               FullName="菜单/首页/首页",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
           new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/MyMenu",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="MyMenu",
               ModuleName="我的",
               Action="MyMenu",
               ActionName="我的",
               FullName="菜单/我的",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/MyMenu/MyMessage",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="MyMenu",
               ModuleName="我的",
               Action="MyMessage",
               ActionName="我的消息",
               FullName="菜单/我的/我的消息",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
              new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/MyMenu/MyAiChat",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="MyMenu",
               ModuleName="我的",
               Action="MyAiChat",
               ActionName="我的AI对话",
               FullName="菜单/我的/我的AI对话",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
             new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/MyMenu/MyAiTasks",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="MyMenu",
               ModuleName="我的",
               Action="MyAiTasks",
               ActionName="我的AI自动任务",
               FullName="菜单/我的/我的AI自动任务",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/MyMenu/MyAiAgents",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="MyMenu",
               ModuleName="我的",
               Action="MyAiAgents",
               ActionName="我的可用智能体",
               FullName="菜单/我的/我的可用智能体",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
               new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/AIManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="AIManagement",
               ModuleName="AI管理",
               Action="AIManagement",
               ActionName="AI管理",
               FullName="菜单/AI管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           }, new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/AIManagement/AIAppsManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="AIManagement",
               ModuleName="AI管理",
               Action="AIAppsManagement",
               ActionName="智能体管理",
               FullName="菜单/AI管理/智能体管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
               new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/AIManagement/AIPromptsManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="AIManagement",
               ModuleName="AI管理",
               Action="AIPromptsManagement",
               ActionName="智能体提示词管理",
               FullName="菜单/AI管理/智能体提示词管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
               new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/AIManagement/AIKmssManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="AIManagement",
               ModuleName="AI管理",
               Action="AIKmssManagement",
               ActionName="知识库管理",
               FullName="菜单/AI管理/知识库管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
               new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/AIManagement/AIModelManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="AIManagement",
               ModuleName="AI管理",
               Action="AIModelManagement",
               ActionName="模型配置管理",
               FullName="菜单/AI管理/模型配置管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
               new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/AIManagement/AISkillToolManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="AIManagement",
               ModuleName="AI管理",
               Action="AISkillToolManagement",
               ActionName="AI技能工具管理",
               FullName="菜单/AI管理/AI技能工具管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
               new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/OrganizationalManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="OrganizationalManagement",
               ModuleName="组织架构",
               Action="OrganizationalManagement",
               ActionName="组织架构",
               FullName="菜单/组织架构",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           } ,
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/OrganizationalManagement/PositionManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="OrganizationalManagement",
               ModuleName="组织架构",
               Action="PositionManagement",
               ActionName="岗位管理",
               FullName="菜单/组织架构/岗位管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           } ,
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/OrganizationalManagement/DepartmentManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="OrganizationalManagement",
               ModuleName="组织架构",
               Action="DepartmentManagement",
               ActionName="部门管理",
               FullName="菜单/组织架构/部门管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/UserManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="UserManagement",
               ModuleName="用户管理",
               Action="UserManagement",
               ActionName="用户管理",
               FullName="菜单/用户管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/UserManagement/UserList",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="UserManagement",
               ModuleName="用户管理",
               Action="UserList",
               ActionName="用户列表",
               FullName="菜单/用户管理/用户列表",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/UserManagement/UserRole",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="UserManagement",
               ModuleName="用户管理",
               Action="UserRole",
               ActionName="角色管理",
               FullName="菜单/用户管理/角色管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/UserManagement/UserPermission",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="UserManagement",
               ModuleName="用户管理",
               Action="UserPermission",
               ActionName="权限管理",
               FullName="菜单/用户管理/权限管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/SystemSettings",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="SystemSettings",
               ModuleName="系统管理",
               Action="SystemSettings",
               ActionName="系统管理",
               FullName="菜单/系统管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/SystemSettings/SystemAnnouncement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="SystemSettings",
               ModuleName="系统管理",
               Action="SystemAnnouncement",
               ActionName="系统公告",
               FullName="菜单/系统管理/系统公告",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/SystemSettings/SystemDic",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="SystemSettings",
               ModuleName="系统管理",
               Action="SystemDic",
               ActionName="系统配置",
               FullName="菜单/系统管理/系统配置",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/SystemSettings/SystemTenant",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="SystemSettings",
               ModuleName="系统管理",
               Action="SystemTenant",
               ActionName="租户管理",
               FullName="菜单/系统管理/租户管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/SystemSettings/SystemCodeGenerator",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="SystemSettings",
               ModuleName="系统管理",
               Action="SystemCodeGenerator",
               ActionName="代码生成器",
               FullName="菜单/系统管理/代码生成器",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/SystemSettings/LogManagement",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="SystemSettings",
               ModuleName="系统管理",
               Action="LogManagement",
               ActionName="日志管理",
               FullName="菜单/系统管理/日志管理",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           },
            new TPermission() {
               Id=TenantHelper.GetSettingsTenantId()+"/Menu/SystemSettings/OsLog",
               PermissionType= 1,
               Area="Menu",
               AreaName="菜单",
               Module="SystemSettings",
               ModuleName="系统管理",
               Action="OsLog",
               ActionName="关键数据变动日志",
               FullName="菜单/系统管理/关键数据变动日志",
               TenantId=TenantHelper.GetSettingsTenantId().ToTryInt32(),
               CreateTime = DateTime.Parse("2020-01-01 00:00:01"),
               IsDelete=false,
               IsManual=true,
               CreateUserId=TUserBaseData.TUsers[0].Id
           }
        };
    }
}
