<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Claims\**" />
    <Compile Remove="Enums\**" />
    <EmbeddedResource Remove="Claims\**" />
    <EmbeddedResource Remove="Enums\**" />
    <None Remove="Claims\**" />
    <None Remove="Enums\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.7.1" />
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\App.Domain.csproj" />
    <ProjectReference Include="..\RepositorieRps\App.RepositorieRps.csproj" />
  </ItemGroup>

</Project>
