<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.7.1" />
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.19" />
    <PackageReference Include="TencentCloudSDK" Version="3.0.1363" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\kevin.Domain.csproj" />
    <ProjectReference Include="..\Kevin.EntityFrameworkCore\Kevin.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\kevin.Module\kevin.Ioc\kevin.Ioc.csproj" />
    <ProjectReference Include="..\kevin.Share\kevin.Domain.Share.csproj" />
  </ItemGroup>

</Project>
